### ISSUE TITLE
Skill tree total stuck at 0

### ISSUE THREAD

**Issue by vFlagR** [MidwestSteeze/ChroniCalc#6]
In the latest release (0.9.7) the skill tree total icon on the left of each skill tree page is not adding up the total amount of skill points spent.

Screenshot to help better understand as my explanation isn't great.

![image](https://user-images.githubusercontent.com/8879581/93371281-00a05f80-f84a-11ea-9607-60c89ef0d6e1.png)

Thanks for all your hard work, Chronicalc has been a massive help in playing the game :)

**Comment by MidwestSteeze** [comment]
@vFlagR Thanks for reporting!  However, I can't seem to reproduce this.  Could you please provide me with the following information?

1)  Were you manually creating a New build, Opening a build, or Importing a build?
  1a)  If you were Opening a build, can you attach or copy/paste the content of the .xml file?
  1b)  If you were Importing a build, can you attach or copy/paste the content of the .build file?

Thank you very much!

**Comment by vFlagR** [comment]
Hey! 

I've done a little testing to try and make this reproducible, here's what I've done: 

1. Use the build share tool to import via Pastebin (here's the one I used: https://pastebin.com/JTd5Y0MD)
2. Export to .build file via Chronicalc
3. Import the exported .build file (Attached)

I _think_ the build export isn't exporting the total number so it's just not there on re-import. I could obviously be wrong :) 

Copy of my exported build file:
`{"class":4,"100339":1,"100339s":20038,"100358":1,"100358s":20018,"100119":1,"100119s":20032,"100101":15,"100101s":20002,"100441":10,"100441s":20104,"100113":1,"100113s":20003,"100031":20,"100031s":20001,"100466":25,"100466s":20106,"100429":1,"100429s":20102,"100110":3,"100110s":20031,"100434":10,"100434s":20103,"100401":103,"100401s":20100,"100123":5,"100123s":20013,"100097":1,"100097s":20028,"100154":1,"100154s":20026,"100117":1,"100117s":20022,"100100":1,"100100s":20009,"100030":20,"100030s":20030,"100356":25,"100356s":20027,"100355":25,"100355s":20017,"100125":5,"100125s":20023,"100107":15,"100107s":20021,"100351":1,"100351s":20016,"100347":25,"100347s":20015,"100145":25,"100145s":20025,"100150":1,"100150s":20007,"100345":5,"100345s":20006,"100133":1,"100133s":20014,"100496":1,"100496s":20118,"100128":5,"100128s":20033,"100421":10,"100421s":20101,"100341":1,"100341s":20005,"100135":1,"100135s":20024,"100115":1,"100115s":20012,"100157":1,"100157s":20036,"100106":15,"100106s":20011,"100148":25,"100148s":20035,"100295":25,"100295s":20008,"100462":1,"100462s":20105,"100023":20,"100023s":20020,"100029":20,"100029s":20010,"100357":1,"100357s":20037,"100121":5,"100121s":20004,"100140":1,"100140s":20034,"100439":10,"100439s":20114,"100426":1,"100426s":20112,"100400":3,"100400s":20110,"100404":10,"100404s":20111,"100433":10,"100433s":20113,"100461":1,"100461s":20115,"100482":25,"100482s":20117,"100467":25,"100467s":20116,"100444":1,"100444s":20125,"100425":1,"100425s":20122,"100402":3,"100402s":20120,"100475":25,"100475s":20127,"100465":25,"100465s":20126,"100406":10,"100406s":20121,"100436":10,"100436s":20124,"100435":10,"100435s":20123,"731":3,"739":3,"185":3,"738":3,"740":3,"737":3,"732":1,"736":3,"729":5,"741":1,"742":2,"735":5,"635":3,"181":5,"645":3,"643":1,"646":3,"223":3,"747":5,"664":5,"675":3,"684":3,"695":1,"175":5,"171":5,"701":3,"685":3,"696":3,"702":3,"699":3,"698":5}`

If I can be of any more assistance please let me know.
Thanks! 

Edit: I forgot to say, after step 1 the skill total does work correctly, it's only after exporting and importing the .build file that the total disappears.

**Comment by MidwestSteeze** [comment]
Thanks @vFlagR very much for following up!  I can reproduce and will get this taken care of ASAP.

**Comment by MidwestSteeze** [comment]
- loading the level of the Passive Bonuses on each Tree, and their corresponding Mastery Row, was causing issues due to a discrepancy in the data (.builds from ChroniCalc vs. .builds from Chronicon), so this functionality has been removed and intsead the Passive Bonuses are now calculated as a running total as each Skill on the Tree, or in the Mastery Row, is imported

This change will be available in the next release (v0.9.8.1005) which should be available within a couple hours at most.
